export {
  checkCoreCompatibility,
  MICROFRONTEND_MANIFEST_SCHEMA_VERSION,
  OPEN_MOVA_CORE_VERSION,
  parseMicrofrontendManifest,
} from './compatibility.js';
export type { CompatibilityResult, OpenMovaMicrofrontendManifest } from './compatibility.js';
export type {
  ActionSheetCapability,
  AppCapability,
  AppLauncherCapability,
  BackgroundRunnerCapability,
  BarcodeScannerCapability,
  BrowserCapability,
  CameraCapability,
  CalendarCapability,
  ClipboardCapability,
  ContactsCapability,
  CookiesCapability,
  DeviceCapability,
  DeviceDetails,
  DialogCapability,
  FileTransferCapability,
  FileViewerCapability,
  FilesystemCapability,
  GeolocationCapability,
  GoogleMapsCapability,
  HapticsCapability,
  HealthFitnessCapability,
  HttpCapability,
  InAppBrowserCapability,
  KeyboardCapability,
  LocalLlmCapability,
  LocalNotificationsCapability,
  MotionCapability,
  NativeCapabilities,
  NativeCapabilityName,
  NativeEvent,
  NativeOptions,
  NativeOperation,
  NativePluginCapability,
  NativeSubscription,
  NetworkCapability,
  PhotoResult,
  PreferencesCapability,
  PrivacyScreenCapability,
  PushNotificationsCapability,
  ScreenOrientationCapability,
  ScreenReaderCapability,
  ShareCapability,
  SplashScreenCapability,
  StatusBarCapability,
  SystemBarsCapability,
  TextZoomCapability,
  ToastCapability,
} from './native.js';
export { NATIVE_CAPABILITIES, NATIVE_CAPABILITY_API, injectNativeCapabilities } from './native.js';
